In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt


In [2]:
#Creating device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device : {device}")

Using device : cuda


In [3]:

X_train = torch.load('tensors/X_train.pt')
y_train = torch.load('tensors/y_train.pt')
X_test = torch.load('tensors/X_test.pt')
y_test = torch.load('tensors/y_test.pt')



In [4]:
class PredictCrowdFundV2(nn.Module):
    def __init__(self):
        super().__init__()
        #using nn.Linear() for creating parameters
        self.linear_layer = nn.Sequential(
            nn.Linear(in_features=4,out_features=8),
            nn.ReLU(),
            nn.Linear(in_features=8,out_features=8),
            nn.ReLU(),
            nn.Linear(in_features = 8,out_features=1)
        )
        
    def forward(self,x:torch.Tensor)->torch.Tensor:
        return self.linear_layer(x)

In [5]:
model1 = PredictCrowdFundV2()
model1.state_dict()

OrderedDict([('linear_layer.0.weight',
              tensor([[ 0.2873, -0.1556, -0.0837, -0.0881],
                      [ 0.1329,  0.2723, -0.1790, -0.1002],
                      [ 0.3004,  0.2250, -0.4864, -0.4926],
                      [-0.1365, -0.1732, -0.3291, -0.0235],
                      [ 0.0766, -0.0454, -0.1752, -0.4153],
                      [ 0.1123, -0.0531, -0.1524,  0.4504],
                      [ 0.4950,  0.4435,  0.2041,  0.4494],
                      [ 0.0080,  0.1351, -0.0162, -0.0926]])),
             ('linear_layer.0.bias',
              tensor([ 0.0230, -0.1796,  0.2421,  0.4813,  0.3807,  0.1940, -0.1684,  0.3375])),
             ('linear_layer.2.weight',
              tensor([[ 0.0757, -0.3177,  0.2160, -0.1185,  0.2687, -0.1698,  0.2581,  0.2292],
                      [ 0.0260, -0.3005, -0.2435,  0.0654, -0.1297, -0.1778,  0.0599,  0.0096],
                      [ 0.3336,  0.2764,  0.1103, -0.0737,  0.0876,  0.1070, -0.0328, -0.0129],
                 

In [6]:
model1.to(device)
next(model1.parameters()).device

device(type='cuda', index=0)

In [7]:
loss_fn = nn.L1Loss()
lr = 0.001

optimizer = torch.optim.SGD(params = model1.parameters(),lr = lr)


c:\Users\aksha\anaconda2\envs\aipytorch\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [38]:
# epochs = 5000
# #Put data on target device
# X_train = X_train.to(device)
# X_test = X_test.to(device)
# y_train = y_train.to(device)
# y_test = y_test.to(device)

# for epoch in range(epochs):
#     model1.train()
#     y_pred = model1(X_train.type(torch.float32))
#     loss = loss_fn(y_pred,y_train)
#     optimizer.zero_grad()
#     loss.backward()
#     optimizer.step()
#     print(loss)

model1 = torch.load('tensors/crowdfunding.pth')
    
model1.eval()
# with torch.inference_mode():
#     test_pred = model1(X_test.type(torch.float32))
#     test_loss = loss_fn(test_pred,y_test)
#     print(test_loss)

tensor(0.5150, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor(0.5115, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor(0.5087, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor(0.5063, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor(0.5044, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor(0.5031, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor(0.5020, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor(0.5011, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor(0.5002, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor(0.4994, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor(0.4988, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor(0.4983, device='cuda:0', dtype=torch.float64, grad_fn=<MeanBackward0>)
tensor(0.4979, device='cuda:0', dtype=torch.float64, grad_fn=<Me

In [47]:
torch.save(model1.state_dict(), 'tensors/crowdfunding2.pth')
